awk '/if \(!std.mem.eql\(u8, family, "daemon"\)\) \{/ {
  print "    if (std.mem.eql(u8, family, \"capture\")) {"
  print "        if (argv.len < 3) {"
  print "            try writeErrorJson(io, \"capture\", \"ERR_CLI_USAGE\", \"usage: shaula capture <area|fullscreen|window> --json\", false);"
  print "            return 1;"
  print "        }"
  print "        const cmd = argToSlice(argv[2]);"
  print "        if (std.mem.eql(u8, cmd, \"area\")) {"
  print "            var json_mode = false;"
  print "            var dry_run = false;"
  print "            var aspect: ?[]const u8 = null;"
  print "            var simulate_cancel = false;"
  print "            var i: usize = 3;"
  print "            while (i < argv.len) : (i += 1) {"
  print "                const arg = argToSlice(argv[i]);"
  print "                if (std.mem.eql(u8, arg, \"--json\")) {"
  print "                    json_mode = true;"
  print "                } else if (std.mem.eql(u8, arg, \"--dry-run\")) {"
  print "                    dry_run = true;"
  print "                } else if (std.mem.eql(u8, arg, \"--simulate-cancel\")) {"
  print "                    simulate_cancel = true;"
  print "                } else if (std.mem.eql(u8, arg, \"--aspect\")) {"
  print "                    if (i + 1 < argv.len) {"
  print "                        i += 1;"
  print "                        aspect = argToSlice(argv[i]);"
  print "                    }"
  print "                }"
  print "            }"
  print "            if (!json_mode) {"
  print "                try writeErrorJson(io, \"capture area\", \"ERR_CLI_USAGE\", \"--json is required\", false);"
  print "                return 1;"
  print "            }"
  print "            const selection = @import(\"selection/selection.zig\");"
  print "            const overlay = @import(\"overlay/overlay.zig\");"
  print "            const result = try overlay.runSelection(.freeform, .{ .aspect = aspect }, dry_run, simulate_cancel);"
  print "            if (result.cancelled) {"
  print "                try writeErrorJson(io, \"capture area\", \"ERR_SELECTION_CANCELLED\", \"selection was cancelled by user\", false);"
  print "                return 1;"
  print "            }"
  print "            const ts = try nowIso8601(allocator, io);"
  print "            defer allocator.free(ts);"
  print "            const aspect_str = if (result.aspect) |a| try std.fmt.allocPrint(allocator, \"\\\"{s}\\\"\", .{a}) else \"null\";"
  print "            defer if (result.aspect != null) allocator.free(aspect_str);"
  print "            var stdout_buffer: [4096]u8 = undefined;"
  print "            var stdout = std.Io.File.stdout().writer(io, &stdout_buffer);"
  print "            try stdout.interface.print("
  print "                \"{{\\\"ok\\\":true,\\\"contract_version\\\":\\\"{s}\\\",\\\"command\\\":\\\"capture area\\\",\\\"timestamp\\\":\\\"{s}\\\",\\\"result\\\":{{\\\"selection\\\":{{\\\"mode\\\":\\\"{s}\\\",\\\"aspect\\\":{s},\\\"cancelled\\\":false}}}},\\\"warnings\\\":[]}}\\n\","
  print "                .{ protocol.contract_version, ts, @tagName(result.mode), aspect_str },"
  print "            );"
  print "            try stdout.interface.flush();"
  print "            return 0;"
  print "        }"
  print "        try writeErrorJson(io, \"capture\", \"ERR_CLI_USAGE\", \"unsupported capture subcommand\", false);"
  print "        return 1;"
  print "    }"
  print ""
}
1' src/main.zig > src/main_patched.zig && mv src/main_patched.zig src/main.zig
